server:
  port: 8222
spring:
  cloud:
    gateway:
      routes:
        - id: swiggy-app
          uri: http://localhost:8081
          predicates:
            - Path=/swiggy/**
          filters:
            - AuthenticationFilter
        - id: stats
          uri: http://localhost:8090
          predicates:
            - Path=/stats/**
          filters:
            - AuthenticationFilter
        - id: members
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/members/**
          filters:
            - AuthenticationFilter
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**
          filters:
            - AuthenticationFilter

        - id: security
          uri: http://localhost:9898
          predicates:
            - Path=/auth/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
  application:
    name: SWIGGY-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/