eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: stats
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/stats/**
        - id: members
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/members/**
        - id: security
          uri: http://localhost:9898
          predicates:
            - Path=/auth/**
  config:
    import: optional:configserver:http://localhost:8888
