hostname: localhost
client:
  service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8090
spring:
  application:
    name: stat
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stats
    username: postgres
    password: root
  flyway:
    locations: classpath:db/migration
    enabled: true
    baselineOnMigrate: true
    cleanDisabled: false
    cleanOnValidationError: true
    clean-on-startup: true
  jpa:
    hibernate:
      ddl-auto: drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
